
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: pgx_tests
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libclang-dev build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache pkg-config

    - name: Install PostgreSQL Client
      run: sudo apt-get install -y postgresql-client

    - name: Install pgx
      run: cargo install --locked cargo-pgrx

    - name: Initialize pgx
      run: cargo pgrx init --pg16 /usr/bin/pg_config

    - name: Build and test
      env:
        PGUSER: postgres
        PGPASSWORD: password
        PGHOST: localhost
        PGPORT: 5432
      run: cargo pgrx test
